#!/usr/bin/env bash
set -euo pipefail
export GIT_TERMINAL_PROMPT=0
export GCM_INTERACTIVE=Never

# --scheduled：由 daily_public_release.ps1 -Scheduled 帶落嚟。argv token 先係
# 自動成功憑證；env CARDZ_DAILY_CHAIN 只係陪跑（stamp 對數）。
STAMP_ARGS=()
for arg in "$@"; do
  case "$arg" in
    --scheduled) STAMP_ARGS+=(--scheduled) ;;
    *) printf 'daily_public_release.sh: unknown arg %s\n' "$arg" >&2; exit 2 ;;
  esac
done
stamp_autonomy() {
  local rc=0
  python3 -X utf8 "$SOURCE_REPO/scripts/stamp_daily_chain_autonomy.py" \
    --generation "$1" --generated-at "$2" --outcome "$3" "${STAMP_ARGS[@]}" || rc=$?
  if ((rc != 0)); then
    printf 'daily release: autonomy stamp FAILED rc=%s outcome=%s generation=%s (publish itself succeeded)\n' "$rc" "$3" "$1" >&2
  fi
  return "$rc"
}

SOURCE_REPO="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
RELEASE_REPO="/home/jackson0202/cardz-market-cap-release-daily"
LOCK_FILE="/tmp/cardz-market-cap-daily-release.lock"

exec 9>"$LOCK_FILE"
flock -n 9

NOTIFY_PY="$SOURCE_REPO/scripts/notify_hermes.py"
RELEASE_STAGE="preflight"
notify_release() {
  if [[ -f "$NOTIFY_PY" ]]; then
    python3 -X utf8 "$NOTIFY_PY" release "$@" || true
  fi
}
on_release_exit() {
  local rc=$?
  if (( rc != 0 )); then
    notify_release --outcome failed --stage "$RELEASE_STAGE" --exit-code "$rc" --generation "${generation:-}"
  fi
}
trap on_release_exit EXIT

test -e "$RELEASE_REPO/.git"
# 條鏈自己每次都會重新生成 data/public/seed-snapshot.json 同
# data/public/market-assets/*.webp，所以嗰條路徑下面嘅殘留冇保留價值。
# 舊版係 `test -z "$(git status --porcelain)"`：只要有一次 run 死喺後面
# （2026-08-11 個 asset gate 就係咁），prune 掉嘅 159 個 sha 會留低 160 行未
# commit 嘅刪除，之後每一日 09:30 都會死喺呢一行，要人手入去 checkout 先郁得返。
# 自己 reset 返自己嘅輸出；data/public 以外有任何未 commit 嘅嘢就照樣硬死，
# 唔會靜靜蓋走人手改動。
if [[ -n "$(git -C "$RELEASE_REPO" status --porcelain -- ':!data/public')" ]]; then
  printf 'daily release refused: uncommitted changes outside data/public\n' >&2
  git -C "$RELEASE_REPO" status --porcelain -- ':!data/public' >&2
  exit 1
fi
git -C "$RELEASE_REPO" checkout -- data/public
git -C "$RELEASE_REPO" fetch origin main
# 對 FETCH_HEAD 快進，唔好淨係 assert 相等。原意係「一定要由 main 嗰個 tree
# bake」，但 assert 版本嘅副作用係：source repo 每次推一個 code commit 上 main，
# release repo 就即刻落後，之後每一次自動發佈都會死喺呢一行，要人手入去 pull。
# --ff-only 保住原意（唔會接受分叉），同時令條鏈自己追返 main。
# 比 FETCH_HEAD 唔好比 refs/remotes/origin/main：release repo 個
# remote.origin.fetch 曾經係空（冇 refspec），origin/main 永遠停喺 clone 嗰刻。
BEFORE="$(git -C "$RELEASE_REPO" rev-parse HEAD)"
git -C "$RELEASE_REPO" merge --ff-only FETCH_HEAD
test -f "$RELEASE_REPO/node_modules/typescript/bin/tsc"

# The release checkout is the exact tree that will bake. Run no-DB guards
# from that tree after the fast-forward and before the first generated byte.
# Snapshot-only ff 跳過 FE／pipelines／script tests；validate self-test 仍然跑。
TEST_PY="/home/jackson0202/cardz-market-cap/.venv-backend/bin/python"
test -x "$TEST_PY"
# Diff against the last tree that PASSED the guards, not this run's ff.
# A dead slot after ff used to leave CHANGED empty → every later slot skipped tests.
TESTED_MARK="$RELEASE_REPO/.git/cardz-last-tested-head"
BASE="$(cat "$TESTED_MARK" 2>/dev/null || true)"
git -C "$RELEASE_REPO" cat-file -e "${BASE:-nonexistent}^{commit}" 2>/dev/null || BASE="$BEFORE"
CHANGED="$(git -C "$RELEASE_REPO" diff --name-only "$BASE" HEAD || true)"
TEST_ARGS=(--no-db)
if ! echo "$CHANGED" | grep -Eq '^(apps/web/|packages/|scripts/test-)'; then
  TEST_ARGS+=(--skip-fe)
fi
if ! echo "$CHANGED" | grep -Eq '^(pipelines/|scripts/)'; then
  TEST_ARGS+=(--skip-pipelines)
fi
if ! echo "$CHANGED" | grep -Eq '^(pipelines/|scripts/|apps/web/|packages/)'; then
  TEST_ARGS+=(--skip-script-tests)
fi
if "$TEST_PY" -X utf8 "$RELEASE_REPO/scripts/run_all_tests.py" --help 2>/dev/null | grep -q -- '--skip-fe'; then
  "$TEST_PY" -X utf8 "$RELEASE_REPO/scripts/run_all_tests.py" "${TEST_ARGS[@]}"
else
  "$TEST_PY" -X utf8 "$RELEASE_REPO/scripts/run_all_tests.py" --no-db
fi
git -C "$RELEASE_REPO" rev-parse HEAD > "$TESTED_MARK"

# PC 成交 title↔卡號矛盾隔離 receipt（runbook 形狀 29）：bake 之前一定要由判別器
# 重新生成，唔准食舊檔。讀者（live-db-snapshot.ts loadSaleQuarantine）fail-closed：
# 冇 receipt 就 bake 死；呢一步負責「有而且唔過期」。用 SOURCE repo 嘅腳本係因為
# receipt 寫入 SOURCE 嘅 data/runtime（bake 個 CARDZ_REPO_ROOT 都係指 SOURCE）。
"$TEST_PY" -X utf8 "$SOURCE_REPO/pipelines/pc_sale_title_quarantine.py"

# Bake 喺 release checkout 跑。佢內建 prune 只識 PSA10 seed，會當 BOX sidecar
# 897 張圖係 stale 搬走。037 sync 跟住又要 SOURCE（fe-db）有呢 897 張——
# BOX 圖只活喺 release git，從來冇入 PSA10 source。2026-08-15 朝鏈／11:30
# 就係咁：prune movedFiles=897，sync「source tree is missing 897」，retry
# 位（11:30／16:30）撞同一個洞，當日 [deploy] 出唔到。
# --no-prune 交俾下面 SOURCE sync：PSA10 由 source 抄，BOX 留 dest，多餘先刪。
publish_assets() {
  CARDZ_REPO_ROOT="$SOURCE_REPO" node "$RELEASE_REPO/scripts/bake-public-snapshot.mjs" \
    --output "$RELEASE_REPO/data/public/seed-snapshot.json" \
    --no-prune
  python3 -X utf8 "$SOURCE_REPO/scripts/sync_public_release_assets.py" \
    --snapshot "$RELEASE_REPO/data/public/seed-snapshot.json" \
    --source "$SOURCE_REPO/data/public/market-assets" \
    --destination "$RELEASE_REPO/data/public/market-assets"
  python3 -X utf8 "$RELEASE_REPO/scripts/validate_daily_release.py" \
    --snapshot "$RELEASE_REPO/data/public/seed-snapshot.json" \
    --assets "$RELEASE_REPO/data/public/market-assets"
}

asset_attempt=1
while true; do
  if publish_assets; then
    break
  fi
  if ((asset_attempt >= 3)); then
    printf 'daily release bake/sync/validate failed after %s attempts\n' "$asset_attempt" >&2
    exit 1
  fi
  asset_attempt=$((asset_attempt + 1))
  printf 'daily release bake/sync/validate retry %s/3\n' "$asset_attempt" >&2
  git -C "$RELEASE_REPO" checkout -- data/public
  sleep 15
done

mapfile -t changed < <(git -C "$RELEASE_REPO" status --porcelain=v1 | sed 's/^...//')

# snapshot 有三個 run-stamp —— 唔係數據，係「我幾時跑咗」：
#   generation.generatedAt      bake 嘅 wall clock（live-db-snapshot.ts:564）
#   generation.effectiveAt      max(metric_accepted_at, price_observed_date,
#                               population_effective_at)（:552-553），而
#                               metric_accepted_at 係 daily-accept 每次 run 嘅 now()
#   currencies.rates.USD.asOf   USD 恆等於 1，佢個 asOf 直接借 effectiveAt（:556）
# 三個喺零數據改動嘅情況下一樣會郁，所以「淨係 pop generatedAt」嘅舊版 fire 唔到：
# 任何行過 daily-accept 嘅 slot 都會推一個內容一模一樣嘅 commit 上 main 兼觸發一次
# 部署（實測 2026-08-11 13:29 commit 61f1ad3b，3 行 diff 全部係呢三個 stamp）。
# 真數據郁嗰陣卡本身嗰啲欄一定跟住郁，個 diff 唔會空，所以 pop 呢三個唔會食咗真更新。
# 將來多一個 run-stamp，個閘只會停止 fire（照推一個多餘 commit），唔會漏推。
if [[ ${#changed[@]} -eq 1 && ${changed[0]} == data/public/seed-snapshot.json ]] \
   && git -C "$RELEASE_REPO" show HEAD:data/public/seed-snapshot.json \
      | python3 -c 'import json,sys
RUN_STAMPS=(("generation","generatedAt"),("generation","effectiveAt"),("currencies","rates","USD","asOf"))
def strip(doc):
    for path in RUN_STAMPS:
        node=doc
        for key in path[:-1]:
            node=node.get(key) if isinstance(node,dict) else None
        if isinstance(node,dict): node.pop(path[-1],None)
    return doc
sys.exit(0 if strip(json.load(sys.stdin))==strip(json.load(open(sys.argv[1]))) else 1)' "$RELEASE_REPO/data/public/seed-snapshot.json"; then
  git -C "$RELEASE_REPO" checkout -- data/public/seed-snapshot.json
  changed=()
fi

if ((${#changed[@]} == 0)); then
  # 冇嘢要推唔等於出咗街。條鏈試過推咗 commit 但公開站冇跟上（見 docs 嘅 deploy
  # postmortem），嗰陣每一日都會report「no-change」然後大家以為正常。
  # 所以冇變都要對一次 live，唔啱就大聲死，等下一個 retry slot 再試。
  generation="$(python3 -c 'import json,sys; print(json.load(open(sys.argv[1]))["generation"]["id"])' "$RELEASE_REPO/data/public/seed-snapshot.json")"
  live="$(curl --fail --silent --show-error --max-time 20 https://app.cardzmarketcap.com/api/health || true)"
  live_generation="$(PUBLIC_HEALTH="$live" python3 -c 'import json,os; print(json.loads(os.environ["PUBLIC_HEALTH"]).get("generation",""))' 2>/dev/null || true)"
  if [[ "$live_generation" == "$generation" ]]; then
    generated_at="$(python3 -c 'import json,sys; print(json.load(open(sys.argv[1]))["generation"]["generatedAt"])' "$RELEASE_REPO/data/public/seed-snapshot.json")"
    stamp_rc=0
    stamp_autonomy "$generation" "$generated_at" no-change || stamp_rc=$?
    notify_release --outcome no-change --generation "$generation"
    printf '{"dailyRelease":"no-change","generation":"%s"}\n' "$generation"
    if ((stamp_rc != 0)); then
      printf 'autonomy stamp failed rc=%s (release itself succeeded)\n' "$stamp_rc" >&2
      exit 3
    fi
    exit 0
  fi
  printf 'release repo already carries %s but live serves %s\n' "$generation" "${live_generation:-<unreachable>}" >&2
  exit 1
fi

for path in "${changed[@]}"; do
  case "$path" in
    data/public/seed-snapshot.json|data/public/box-subset.json|data/public/market-assets/*.webp) ;;
    *) printf 'daily release refused unexpected path: %s\n' "$path" >&2; exit 1 ;;
  esac
done
for path in "${changed[@]}"; do
  git -C "$RELEASE_REPO" add -- "$path"
done

generation="$(python3 -c 'import json,sys; print(json.load(open(sys.argv[1]))["generation"]["id"])' "$RELEASE_REPO/data/public/seed-snapshot.json")"
generated_at="$(python3 -c 'import json,sys; print(json.load(open(sys.argv[1]))["generation"]["generatedAt"])' "$RELEASE_REPO/data/public/seed-snapshot.json")"
git -C "$RELEASE_REPO" commit -m "release: daily CARDZ 037 FE04 $generation [deploy]"
push_attempt=1
until git -C "$RELEASE_REPO" push origin HEAD:main; do
  if ((push_attempt >= 3)); then
    printf 'daily release push failed after %s attempts\n' "$push_attempt" >&2
    exit 1
  fi
  push_attempt=$((push_attempt + 1))
  printf 'daily release push retry %s/3\n' "$push_attempt" >&2
  sleep 15
done

for _ in $(seq 1 60); do
  if body="$(curl --fail --silent --show-error https://app.cardzmarketcap.com/api/health)"; then
    # 判「新 bundle 上到未」睇 generatedAt（每次 bake 都變，由 snapshot 自己帶），
    # 唔再睇 build。build 要部署方 set CARDZ_PUBLIC_BUILD_ID，而實際 deploy 路徑
    # 由頭到尾冇 set 過，永遠係 "local"，所以舊 gate 恆假：每次都白等足 10 分鐘
    # 然後報 fail，明明個站已經更新咗。
    if PUBLIC_HEALTH="$body" python3 -c 'import json,os,sys; h=json.loads(os.environ["PUBLIC_HEALTH"]); sys.exit(0 if h.get("status")=="ok" and h.get("generation")==sys.argv[1] and h.get("generatedAt")==sys.argv[2] else 1)' "$generation" "$generated_at"; then
      stamp_rc=0
      stamp_autonomy "$generation" "$generated_at" published || stamp_rc=$?
      notify_release --outcome published --generation "$generation"
      printf '%s\n' "$body"
      if ((stamp_rc != 0)); then
        printf 'autonomy stamp failed rc=%s (release itself succeeded)\n' "$stamp_rc" >&2
        exit 3
      fi
      exit 0
    fi
  fi
  sleep 10
done

printf 'public release did not reach generation %s (generatedAt %s) within 10 minutes\n' "$generation" "$generated_at" >&2
exit 1
