#!/usr/bin/env python3
"""Generate the public TypeScript release-policy contract from routing config."""

from __future__ import annotations

import argparse
import hashlib
import json
from pathlib import Path
from typing import Any


ROOT = Path(__file__).resolve().parents[1]
ROUTING_CONFIG = ROOT / "config" / "data-routing.json"
OUTPUT = ROOT / "packages" / "market-data" / "src" / "release-policy.generated.ts"


def canonical_json_bytes(value: Any) -> bytes:
    return (
        json.dumps(value, ensure_ascii=False, separators=(",", ":"), sort_keys=True).encode("utf-8")
        + b"\n"
    )


def policy_sha256(profile_id: str, policy: dict[str, Any]) -> str:
    return hashlib.sha256(
        canonical_json_bytes({"releaseProfile": profile_id, "policy": policy})
    ).hexdigest()


def generated_source(document: dict[str, Any]) -> str:
    profiles = document.get("releaseProfiles")
    public_policy = document.get("publicReleasePolicy")
    if not isinstance(profiles, dict) or not profiles:
        raise ValueError("releaseProfiles must be a non-empty object")
    if not isinstance(public_policy, dict) or not public_policy:
        raise ValueError("publicReleasePolicy must be a non-empty object")

    normalized: dict[str, dict[str, Any]] = {}
    default_profile = document.get("defaultReleaseProfile")
    if not isinstance(default_profile, str) or default_profile not in profiles:
        raise ValueError("defaultReleaseProfile must name one releaseProfiles entry")
    for profile_id in sorted(profiles):
        policy = profiles[profile_id]
        if not isinstance(profile_id, str) or not isinstance(policy, dict):
            raise ValueError("releaseProfiles must map string ids to policy objects")
        for field in (
            "allowedIdentityStatuses",
            "priceFreshnessHoursMaximum",
            "populationFreshnessHoursMaximum",
            "trackedPsa10Sales30dMinimumInclusive",
            "requestedCount",
            "minimumVerifiedCount",
            "publicCardsMaximum",
            "publicImageAssetsMaximum",
        ):
            if field not in policy:
                raise ValueError(f"release profile {profile_id!r} is missing {field}")
        normalized[profile_id] = {
            "policy": policy,
            "policySha256": policy_sha256(profile_id, policy),
        }
    default_policy = profiles[default_profile]
    if not isinstance(default_policy, dict) or any(
        default_policy.get(field) != value for field, value in public_policy.items()
    ):
        raise ValueError(
            "publicReleasePolicy must match defaultReleaseProfile"
        )

    rendered = json.dumps(normalized, ensure_ascii=False, indent=2, sort_keys=True)
    profile_ids = " | ".join(json.dumps(profile_id) for profile_id in sorted(normalized))
    rendered_default_profile = json.dumps(default_profile)
    return f'''// Generated by scripts/generate_release_policy.py from config/data-routing.json. Do not edit.

export type ReleaseProfileId = {profile_ids};

export const DEFAULT_RELEASE_PROFILE: ReleaseProfileId = {rendered_default_profile};

export const RELEASE_POLICY_PROFILES = {rendered} as const;

export function isReleaseProfileId(value: unknown): value is ReleaseProfileId {{
  return typeof value === "string" && value in RELEASE_POLICY_PROFILES;
}}
'''


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true", help="fail when generated output is stale")
    parser.add_argument("--stdout", action="store_true", help="print generated output without writing")
    args = parser.parse_args()
    if args.check and args.stdout:
        raise SystemExit("--check and --stdout cannot be used together")

    document = json.loads(ROUTING_CONFIG.read_text(encoding="utf-8"))
    source = generated_source(document)
    if args.stdout:
        print(source, end="")
        return
    if args.check:
        actual = OUTPUT.read_text(encoding="utf-8") if OUTPUT.exists() else ""
        if actual != source:
            raise SystemExit(f"generated release policy is stale: {OUTPUT}")
        return
    OUTPUT.write_text(source, encoding="utf-8")


if __name__ == "__main__":
    main()
