// Generated by scripts/generate_release_policy.py from config/data-routing.json. Do not edit.

export type ReleaseProfileId = "relaxed-launch-v1" | "strict-v1";

export const DEFAULT_RELEASE_PROFILE: ReleaseProfileId = "relaxed-launch-v1";

export const RELEASE_POLICY_PROFILES = {
  "relaxed-launch-v1": {
    "policy": {
      "acceptedBootstrapSources": {
        "data": [
          "grade10"
        ],
        "images": [
          "grade10"
        ]
      },
      "allPoolFailureAction": "per_card_exclude",
      "allowedIdentityStatuses": [
        "confirmed",
        "provisional"
      ],
      "coverageClaims": [
        "verified-top-n",
        "verified-top-100"
      ],
      "identityConflictAction": "block",
      "identityStatus": "provisional",
      "imageHardExclusions": [
        "not_public_allowed",
        "not_raw_front",
        "asset_unreadable",
        "content_hash_invalid",
        "geometry_invalid",
        "sample_or_placeholder",
        "human_rejected",
        "cross_card_duplicate",
        "cross_tcg_duplicate"
      ],
      "imageHumanReviewRequired": false,
      "imageSemanticStatus": "highest_confidence_eligible",
      "lastGoodMaximumHours": 720,
      "minimumExactAuthorityBindings": 1,
      "minimumVerifiedCount": 100,
      "pointerPromotion": "generation_bound_atomic_last",
      "populationFreshnessHoursMaximum": 168,
      "priceFreshnessHoursMaximum": 720,
      "priceSelection": "pricecharting_explicit_psa10_then_ebay_exact_psa10_sold_median_then_snk_exact_psa10",
      "priceSpreadAction": "warning",
      "priceSpreadMaximumRatio": 2.0,
      "publicCardsMaximum": 1000,
      "publicImageAssetsMaximum": 3000,
      "publisher": "pipelines/publish-snapshot.mjs",
      "recognizedIdentityAuthorities": [
        "gemrate",
        "snk",
        "pricecharting",
        "psa"
      ],
      "requestedCount": 100,
      "requireCanonicalPrinting": false,
      "requireCompleteSevenPartPrinting": true,
      "trackedPsa10Sales30dMinimumInclusive": 5
    },
    "policySha256": "5c7c7aa96f5669379d3436ce2d3c04c2dfe1972a5feba70c319ec91e066f4125"
  },
  "strict-v1": {
    "policy": {
      "acceptedBootstrapSources": {
        "data": [],
        "images": []
      },
      "allPoolFailureAction": "block_release",
      "allowedIdentityStatuses": [
        "confirmed"
      ],
      "coverageClaims": [
        "verified-top-n",
        "verified-top-100"
      ],
      "identityConflictAction": "block",
      "identityStatus": "confirmed",
      "imageHardExclusions": [
        "not_public_allowed",
        "not_raw_front",
        "asset_unreadable",
        "content_hash_invalid",
        "geometry_invalid",
        "sample_or_placeholder",
        "human_rejected",
        "cross_card_duplicate",
        "cross_tcg_duplicate"
      ],
      "imageHumanReviewRequired": true,
      "imageSemanticStatus": "human_or_vision_confirmed",
      "lastGoodMaximumHours": 48,
      "minimumExactAuthorityBindings": 1,
      "minimumVerifiedCount": 1,
      "pointerPromotion": "generation_bound_atomic_last",
      "populationFreshnessHoursMaximum": 168,
      "priceFreshnessHoursMaximum": 48,
      "priceSelection": "arithmetic_mean_of_fresh_authority_families",
      "priceSpreadAction": "block",
      "priceSpreadMaximumRatio": 2.0,
      "publicCardsMaximum": 500,
      "publicImageAssetsMaximum": 1500,
      "publisher": "pipelines/publish-snapshot.mjs",
      "recognizedIdentityAuthorities": [
        "gemrate"
      ],
      "requestedCount": 100,
      "requireCanonicalPrinting": true,
      "requireCompleteSevenPartPrinting": true,
      "trackedPsa10Sales30dMinimumInclusive": 10
    },
    "policySha256": "9467184ec0f4d2ad6b355a54331a419e2de154ab491a8f1507ff4beb2abaf909"
  }
} as const;

export function isReleaseProfileId(value: unknown): value is ReleaseProfileId {
  return typeof value === "string" && value in RELEASE_POLICY_PROFILES;
}
