/* Prestige taglines：100 句已批核英文 slogan + 四語翻譯。
   footer / 404 用 pickTagline（slot+UTC 日期 deterministic，每日輪換、人人同句），
   share image 用 pickRandomTagline（click-time Math.random，同 pickShareTheme 一樣）。 */
import type { Locale } from "./types";

export const TAGLINE_COUNT = 100;

const en = [
  "Not every card earns a place on this board.",
  "Listed only when the market says it's ready.",
  "Where demand proves itself before it appears.",
  "The board opens only for cards with real gravity.",
  "Admission is earned in volume, not in noise.",
  "We list conviction, not speculation.",
  "A card arrives here when the market can no longer ignore it.",
  "Thresholds are quiet. Results are loud.",
  "Some cards knock. Ours are already inside.",
  "The door is narrow by design.",
  "Signal over noise, always.",
  "The market whispers. We listen in high fidelity.",
  "Intelligence, rendered in real time.",
  "Where data becomes discernment.",
  "Reading the market like an art form.",
  "The pulse of the collectible economy.",
  "Every movement, measured. Every signal, earned.",
  "Precision is our native language.",
  "See the market the way insiders feel it.",
  "Noise is free. Signal is curated.",
  "Where cardboard becomes blue-chip.",
  "The art market, quantified.",
  "Collectibles, priced like the assets they are.",
  "Every card is a canvas; every price a critique.",
  "The gallery where value is painted in real time.",
  "From binder to balance sheet.",
  "Collecting is culture. Pricing is craft.",
  "The museum of market momentum.",
  "Fine art energy, trading-floor precision.",
  "Where passion meets price discovery.",
  "The future of collecting has a dashboard.",
  "Tomorrow's blue chips, visible today.",
  "Built for the collectors of the next decade.",
  "Yesterday's hobby. Tomorrow's asset class.",
  "We don't predict the future. We chart it arriving.",
  "The next era of collectibles starts on this screen.",
  "Foresight, formatted.",
  "Watch the future appreciate.",
  "The horizon, indexed.",
  "The market is moving. So are we — faster.",
  "Momentum you can see.",
  "The market never sleeps. Neither does the board.",
  "Velocity, visualized.",
  "Where momentum becomes a map.",
  "Every tick tells a story.",
  "Movement is the message.",
  "The fastest read in the card market.",
  "Speed is a feature. Accuracy is the promise.",
  "Catch the wave before it crests.",
  "Always in motion. Never in doubt.",
  "Curated by the market itself.",
  "The few. The traded. The listed.",
  "Excellence has a waiting list.",
  "Not the most cards. The right cards.",
  "A smaller board. A bigger signal.",
  "Where quality is the entry fee.",
  "The shortlist the market wrote.",
  "Elite by evidence.",
  "Provenance meets performance.",
  "Only the proven make the cut.",
  "The market, painted in heat.",
  "A thousand trades, one picture.",
  "See value. Literally.",
  "Color-coded conviction.",
  "The heat never lies.",
  "A portrait of demand, redrawn daily.",
  "Watch capital change color.",
  "The canvas where markets confess.",
  "Beauty, backed by volume.",
  "Every tile a verdict.",
  "Method over hype.",
  "Built slowly. Shipped carefully. Trusted daily.",
  "No noise. No filler. Just the board.",
  "Discipline is the design.",
  "The quiet confidence of clean data.",
  "Standards first. Everything else follows.",
  "Measured twice, published once.",
  "We take the market seriously so you can enjoy it.",
  "Rigor you don't have to think about.",
  "Craft in every cell.",
  "One board. Every card culture.",
  "From Tokyo to your screen, in one glance.",
  "The world's binders, one market.",
  "Collecting is universal. So is the board.",
  "Where the hobby speaks every language.",
  "Global demand, local legends.",
  "The culture, capitalized.",
  "Every grail has a market. This is its home.",
  "Across eras, across franchises, one truth: the tape.",
  "The collector's index of record.",
  "Earned, not listed.",
  "Demand, depicted.",
  "Value, visible.",
  "The board knows.",
  "Priced by proof.",
  "Heat with history.",
  "Signal, framed.",
  "Where cards graduate.",
  "The standard, visualized.",
  "This is where the market looks.",
];

const zhTW = [
  "並非每張卡，都有資格登上這個榜。",
  "唯有市場說準備好了，才會上榜。",
  "需求先證明自己，才在此現身。",
  "這個榜，只為真正有份量的卡而開。",
  "入場資格靠成交賺取，不靠喧囂。",
  "我們收錄信念，不收錄炒作。",
  "當市場再也無法忽視它，它便來到這裡。",
  "門檻無聲，結果響亮。",
  "有些卡還在敲門，我們的早已入席。",
  "門，刻意做得窄。",
  "訊號永遠先於噪音。",
  "市場低語，我們以高保真聆聽。",
  "情報，即時呈現。",
  "數據在此化為眼光。",
  "讀市場，如讀一門藝術。",
  "收藏經濟的脈搏。",
  "每個波動皆有度量，每個訊號皆是掙來。",
  "精準，是我們的母語。",
  "以行內人的手感，看這個市場。",
  "噪音免費，訊號精選。",
  "紙板在此成為藍籌。",
  "藝術市場，量化呈現。",
  "收藏品，以資產的方式定價。",
  "每張卡都是畫布，每個價格都是評論。",
  "一座價值即時作畫的藝廊。",
  "從卡簿到資產負債表。",
  "收藏是文化，定價是工藝。",
  "市場動能的美術館。",
  "藝術品的氣場，交易大廳的精準。",
  "熱愛與價格發現相遇之處。",
  "收藏的未來，有一面儀表板。",
  "明日的藍籌，今天可見。",
  "為下一個十年的藏家而建。",
  "昨日是嗜好，明日是資產類別。",
  "我們不預測未來，我們繪出它抵達的軌跡。",
  "收藏品的下一個時代，從這個螢幕開始。",
  "遠見，已成格式。",
  "看著未來升值。",
  "地平線，已被編入指數。",
  "市場在動，我們也是——而且更快。",
  "看得見的動能。",
  "市場不眠，榜也不眠。",
  "速度，視覺化。",
  "動能在此成為地圖。",
  "每一跳，都是一個故事。",
  "動，即是訊息。",
  "卡牌市場最快的解讀。",
  "速度是功能，準確是承諾。",
  "在浪尖成形之前趕上它。",
  "永遠在動，從不遲疑。",
  "由市場親自策展。",
  "少數、成交、上榜。",
  "卓越，需要排隊。",
  "不求最多卡，只求對的卡。",
  "更小的榜，更大的訊號。",
  "品質，是這裡的入場費。",
  "市場親筆寫下的候選名單。",
  "以證據論菁英。",
  "來歷與表現交會。",
  "唯有經得起驗證者，得以入選。",
  "市場，以熱度作畫。",
  "千筆成交，一張圖。",
  "看見價值——字面意義上。",
  "以色彩標記的信念。",
  "熱度從不說謊。",
  "一幅每日重繪的需求肖像。",
  "看資本變色。",
  "市場坦白所在的畫布。",
  "美，有成交量撐腰。",
  "每格，都是一紙判決。",
  "方法勝過炒作。",
  "慢慢造，謹慎發，日日可信。",
  "無噪音，無填充，只有榜。",
  "紀律，就是設計。",
  "乾淨數據的安靜自信。",
  "標準先行，其餘隨後。",
  "量兩次，發一次。",
  "我們認真對待市場，讓你安心享受它。",
  "嚴謹到你不必費心。",
  "每格皆見工藝。",
  "一面榜，容納每種卡牌文化。",
  "從東京到你的螢幕，一眼之間。",
  "全世界的卡簿，同一個市場。",
  "收藏無國界，榜也是。",
  "嗜好在此說每一種語言。",
  "全球需求，在地傳奇。",
  "文化，已被資本化。",
  "每件夢幻逸品都有市場，這裡是它的家。",
  "跨越時代與系列，只有一個真相：行情帶。",
  "藏家的官方指數。",
  "是掙來的，不是掛上的。",
  "需求，已成圖。",
  "價值，看得見。",
  "榜知道。",
  "以證據定價。",
  "有歷史的熱度。",
  "訊號，已裝框。",
  "卡在此畢業。",
  "標準，視覺化。",
  "市場，正看向這裡。",
];

const zhCN = [
  "并非每张卡，都有资格登上这个榜。",
  "唯有市场说准备好了，才会上榜。",
  "需求先证明自己，才在此现身。",
  "这个榜，只为真正有分量的卡而开。",
  "入场资格靠成交赚取，不靠喧嚣。",
  "我们收录信念，不收录炒作。",
  "当市场再也无法忽视它，它便来到这里。",
  "门槛无声，结果响亮。",
  "有些卡还在敲门，我们的早已入席。",
  "门，刻意做得窄。",
  "信号永远先于噪音。",
  "市场低语，我们以高保真聆听。",
  "情报，实时呈现。",
  "数据在此化为眼光。",
  "读市场，如读一门艺术。",
  "收藏经济的脉搏。",
  "每个波动皆有度量，每个信号皆是挣来。",
  "精准，是我们的母语。",
  "以行内人的手感，看这个市场。",
  "噪音免费，信号精选。",
  "纸板在此成为蓝筹。",
  "艺术市场，量化呈现。",
  "收藏品，以资产的方式定价。",
  "每张卡都是画布，每个价格都是评论。",
  "一座价值实时作画的画廊。",
  "从卡簿到资产负债表。",
  "收藏是文化，定价是工艺。",
  "市场动能的美术馆。",
  "艺术品的气场，交易大厅的精准。",
  "热爱与价格发现相遇之处。",
  "收藏的未来，有一面仪表盘。",
  "明日的蓝筹，今天可见。",
  "为下一个十年的藏家而建。",
  "昨日是爱好，明日是资产类别。",
  "我们不预测未来，我们绘出它抵达的轨迹。",
  "收藏品的下一个时代，从这个屏幕开始。",
  "远见，已成格式。",
  "看着未来升值。",
  "地平线，已被编入指数。",
  "市场在动，我们也是——而且更快。",
  "看得见的动能。",
  "市场不眠，榜也不眠。",
  "速度，可视化。",
  "动能在此成为地图。",
  "每一跳，都是一个故事。",
  "动，即是讯息。",
  "卡牌市场最快的解读。",
  "速度是功能，准确是承诺。",
  "在浪尖成形之前赶上它。",
  "永远在动，从不迟疑。",
  "由市场亲自策展。",
  "少数、成交、上榜。",
  "卓越，需要排队。",
  "不求最多卡，只求对的卡。",
  "更小的榜，更大的信号。",
  "品质，是这里的入场费。",
  "市场亲笔写下的候选名单。",
  "以证据论精英。",
  "来历与表现交会。",
  "唯有经得起验证者，得以入选。",
  "市场，以热度作画。",
  "千笔成交，一张图。",
  "看见价值——字面意义上。",
  "以色彩标记的信念。",
  "热度从不说谎。",
  "一幅每日重绘的需求肖像。",
  "看资本变色。",
  "市场坦白所在的画布。",
  "美，有成交量撑腰。",
  "每格，都是一纸判决。",
  "方法胜过炒作。",
  "慢慢造，谨慎发，日日可信。",
  "无噪音，无填充，只有榜。",
  "纪律，就是设计。",
  "干净数据的安静自信。",
  "标准先行，其余随后。",
  "量两次，发一次。",
  "我们认真对待市场，让你安心享受它。",
  "严谨到你不必费心。",
  "每格皆见工艺。",
  "一面榜，容纳每种卡牌文化。",
  "从东京到你的屏幕，一眼之间。",
  "全世界的卡簿，同一个市场。",
  "收藏无国界，榜也是。",
  "爱好在此说每一种语言。",
  "全球需求，在地传奇。",
  "文化，已被资本化。",
  "每件梦幻逸品都有市场，这里是它的家。",
  "跨越时代与系列，只有一个真相：行情带。",
  "藏家的官方指数。",
  "是挣来的，不是挂上的。",
  "需求，已成图。",
  "价值，看得见。",
  "榜知道。",
  "以证据定价。",
  "有历史的热度。",
  "信号，已装框。",
  "卡在此毕业。",
  "标准，可视化。",
  "市场，正看向这里。",
];

const ja = [
  "すべてのカードが、このボードに載るわけではない。",
  "市場が「準備ができた」と言うまで、掲載されない。",
  "需要は自らを証明してから、ここに現れる。",
  "このボードは、本物の重力を持つカードだけに開かれる。",
  "掲載資格はノイズではなく、出来高で勝ち取られる。",
  "私たちが載せるのは憶測ではなく、確信だ。",
  "市場がもはや無視できなくなった時、カードはここに辿り着く。",
  "基準は静かに。結果は雄弁に。",
  "叩くカードもある。私たちのカードは、すでに中にいる。",
  "門は、意図的に狭く設計されている。",
  "常にノイズよりシグナルを。",
  "市場は囁く。私たちはハイファイで聴く。",
  "インテリジェンスを、リアルタイムで描く。",
  "データが眼識へと変わる場所。",
  "市場を、ひとつの芸術として読む。",
  "コレクティブル経済の脈拍。",
  "すべての動きを測り、すべてのシグナルを勝ち取る。",
  "精密さは、私たちの母語だ。",
  "インサイダーが感じるように、市場を見る。",
  "ノイズは無料。シグナルはキュレーション。",
  "段ボール紙がブルーチップになる場所。",
  "アート市場を、定量化する。",
  "コレクティブルを、資産としての価格で。",
  "すべてのカードはキャンバス、すべての価格は批評。",
  "価値がリアルタイムで描かれるギャラリー。",
  "バインダーから、貸借対照表へ。",
  "集めることは文化。値付けはクラフト。",
  "市場の運動量の美術館。",
  "美術品の気配、取引所の精度。",
  "情熱と価格発見が出会う場所。",
  "コレクティングの未来には、ダッシュボードがある。",
  "明日のブルーチップを、今日見る。",
  "次の10年のコレクターのために。",
  "昨日の趣味。明日のアセットクラス。",
  "未来は予測しない。到来を描くのだ。",
  "コレクティブルの次の時代は、この画面から始まる。",
  "フォーマットされた先見。",
  "未来が値上がりするのを、見届けよう。",
  "地平線まで、指数化。",
  "市場は動いている。私たちも——もっと速く。",
  "目に見えるモメンタム。",
  "市場は眠らない。ボードも眠らない。",
  "速度を、視覚化。",
  "モメンタムが地図になる場所。",
  "ひとつの刻みが、ひとつの物語。",
  "動きこそがメッセージ。",
  "カード市場で最速の読み。",
  "速さは機能。正確さは約束。",
  "波が砕ける前に、乗る。",
  "常に動き、迷わない。",
  "市場そのものによるキュレーション。",
  "選ばれ、取引され、掲載される。",
  "卓越には、ウェイティングリストがある。",
  "最多のカードではなく、正しいカードを。",
  "小さなボード。大きなシグナル。",
  "ここでは品質が入場料。",
  "市場が書いたショートリスト。",
  "証拠によるエリート。",
  "来歴とパフォーマンスの交差点。",
  "証明されたものだけが、残る。",
  "市場を、熱で描く。",
  "千の取引、一枚の絵。",
  "価値を見る。文字通りに。",
  "色で示された確信。",
  "熱は嘘をつかない。",
  "毎日描き直される、需要の肖像。",
  "資本が色を変えるのを、見る。",
  "市場が告白するキャンバス。",
  "出来高に裏付けられた美。",
  "すべてのタイルが、ひとつの評決。",
  "ハイプより、メソッド。",
  "ゆっくり作り、丁寧に出し、毎日信頼される。",
  "ノイズなし。詰め物なし。ボードだけ。",
  "規律こそがデザイン。",
  "クリーンなデータの、静かな自信。",
  "基準が先。他のすべては後。",
  "二度測り、一度だけ公開する。",
  "市場に真剣に向き合うのは、あなたが楽しめるように。",
  "考えなくていいほどの厳密さ。",
  "すべてのセルに、クラフトを。",
  "ひとつのボード。すべてのカード文化。",
  "東京からあなたの画面へ、ひと目で。",
  "世界のバインダー、ひとつの市場。",
  "コレクティングは普遍的。ボードも同じ。",
  "ホビーがあらゆる言語を話す場所。",
  "グローバルな需要、ローカルなレジェンド。",
  "文化の、資本化。",
  "すべてのグレイルに市場がある。ここがその家。",
  "時代もシリーズも越えて、真実はひとつ。テープだ。",
  "コレクターのための公認指数。",
  "載せられるのではなく、勝ち取る。",
  "需要を、描く。",
  "価値を、可視化。",
  "ボードは知っている。",
  "証拠による価格。",
  "歴史ある熱。",
  "額装されたシグナル。",
  "カードが卒業する場所。",
  "スタンダードを、視覚化。",
  "市場が見ているのは、ここだ。",
];

const ko = [
  "모든 카드가 이 보드에 오르는 것은 아니다.",
  "시장이 준비됐다고 말할 때만 등재된다.",
  "수요는 스스로 증명한 뒤에야 여기 나타난다.",
  "이 보드는 진짜 무게감 있는 카드에게만 열린다.",
  "입장은 소음이 아니라 거래량으로 얻는다.",
  "우리는 투기가 아니라 확신을 싣는다.",
  "시장이 더는 무시할 수 없을 때, 카드는 이곳에 도착한다.",
  "기준은 조용하다. 결과는 요란하다.",
  "문을 두드리는 카도 있다. 우리 카드는 이미 안에 있다.",
  "문은 의도적으로 좁게 만들었다.",
  "언제나 노이즈보다 시그널.",
  "시장은 속삭인다. 우리는 하이파이로 듣는다.",
  "인텔리전스를 실시간으로 렌더링하다.",
  "데이터가 안목이 되는 곳.",
  "시장을 하나의 예술처럼 읽는다.",
  "컬렉터블 경제의 맥박.",
  "모든 움직임은 측정되고, 모든 시그널은 쟁취된다.",
  "정밀함은 우리의 모국어다.",
  "인사이더가 느끼는 그대로 시장을 본다.",
  "노이즈는 공짜, 시그널은 큐레이션.",
  "골판지가 블루칩이 되는 곳.",
  "아트 마켓을 계량화하다.",
  "컬렉터블을 자산답게 가격 매기다.",
  "모든 카드는 캔버스, 모든 가격은 비평.",
  "가치가 실시간으로 그려지는 갤러리.",
  "바인더에서 대차대조표까지.",
  "수집은 문화, 가격 결정은 크래프트.",
  "시장 모멘텀의 미술관.",
  "파인아트의 에너지, 트레이딩 플로어의 정밀함.",
  "열정과 가격 발견이 만나는 곳.",
  "수집의 미래에는 대시보드가 있다.",
  "내일의 블루칩을 오늘 본다.",
  "다음 10년의 컬렉터를 위해 만들었다.",
  "어제의 취미, 내일의 자산군.",
  "우리는 미래를 예측하지 않는다. 도착하는 모습을 그릴 뿐.",
  "컬렉터블의 다음 시대는 이 화면에서 시작된다.",
  "포맷된 통찰.",
  "미래가 오르는 것을 지켜볼 것.",
  "지평선까지 인덱싱.",
  "시장이 움직인다. 우리도 — 더 빠르게.",
  "눈에 보이는 모멘텀.",
  "시장은 잠들지 않는다. 보드도 마찬가지.",
  "속도를 시각화하다.",
  "모멘텀이 지도가 되는 곳.",
  "틱 하나하나가 이야기다.",
  "움직임이 곧 메시지.",
  "카드 시장에서 가장 빠른 판독.",
  "속도는 기능, 정확도는 약속.",
  "파도가 부서지기 전에 올라타라.",
  "항상 움직이되, 흔들리지 않는다.",
  "시장 스스로 큐레이션하다.",
  "선택받고, 거래되고, 등재된 것들.",
  "탁월함에는 대기 명단이 있다.",
  "가장 많은 카드가 아니라, 올바른 카드를.",
  "더 작은 보드, 더 큰 시그널.",
  "여기서 품질은 입장료다.",
  "시장이 직접 쓴 후보 명단.",
  "증거로 입증된 엘리트.",
  "이력과 성과의 만남.",
  "증명된 것만이 살아남는다.",
  "시장을 열기로 그리다.",
  "천 건의 거래, 한 장의 그림.",
  "가치를 본다. 말 그대로.",
  "색으로 표시된 확신.",
  "열기는 거짓말하지 않는다.",
  "매일 다시 그려지는 수요의 초상.",
  "자본이 색을 바꾸는 것을 지켜볼 것.",
  "시장이 고백하는 캔버스.",
  "거래량이 뒷받침하는 아름다움.",
  "타일 하나하나가 평결이다.",
  "과열보다 방법론.",
  "천천히 만들고, 신중히 내놓고, 매일 신뢰받는다.",
  "노이즈도, 군더더기도 없이. 보드만.",
  "절제가 곧 디자인.",
  "깨끗한 데이터의 조용한 자신감.",
  "기준이 먼저, 나머지는 그다음.",
  "두 번 재고, 한 번만 발표한다.",
  "우리가 시장을 진지하게 대하는 건, 당신이 즐길 수 있도록.",
  "신경 쓸 필요 없는 엄밀함.",
  "모든 셀에 장인정신을.",
  "하나의 보드, 모든 카드 문화.",
  "도쿄에서 당신의 화면까지, 한눈에.",
  "전 세계의 바인더, 하나의 시장.",
  "수집은 보편적이다. 보드도 그렇다.",
  "취미가 모든 언어를 말하는 곳.",
  "글로벌한 수요, 로컬의 레전드.",
  "자본화된 문화.",
  "모든 그레일에는 시장이 있다. 여기가 그 집이다.",
  "시대와 프랜차이즈를 넘어, 진실은 하나. 테이프다.",
  "컬렉터의 공인 지수.",
  "등재되는 것이 아니라, 쟁취하는 것.",
  "수요를, 그림으로.",
  "가치를, 눈에 보이게.",
  "보드는 알고 있다.",
  "증거로 매긴 가격.",
  "역사가 있는 열기.",
  "액자에 담긴 시그널.",
  "카드가 졸업하는 곳.",
  "표준을 시각화하다.",
  "시장이 바라보는 곳, 바로 여기.",
];

export const TAGLINES: Record<Locale, string[]> = {
  en,
  "zh-TW": zhTW,
  "zh-CN": zhCN,
  ja,
  ko,
};

/* djb2：同一 slot+seed → 同一條，跨地區/用戶一致；seed 預設 UTC 日期 → 每日輪換 */
function hashTaglineKey(input: string): number {
  let hash = 5381;
  for (let i = 0; i < input.length; i++) {
    hash = ((hash << 5) + hash + input.charCodeAt(i)) | 0;
  }
  return Math.abs(hash);
}

function listFor(locale: Locale): string[] {
  const list = TAGLINES[locale];
  return Array.isArray(list) && list.length >= TAGLINE_COUNT ? list : TAGLINES.en;
}

export function pickTagline(locale: Locale, slot: string, seed?: string): string {
  const day = seed ?? new Date().toISOString().slice(0, 10);
  const list = listFor(locale);
  return list[hashTaglineKey(`${slot}:${day}`) % list.length];
}

export function pickRandomTagline(locale: Locale, random: () => number = Math.random): string {
  const list = listFor(locale);
  return list[Math.floor(random() * list.length) % list.length];
}
